name: main
channels: 
    - defaults
    - conda-forge
dependencies:
    - python=3
    - numpy
    - scipy
    - pandas
    - jupyter
    - matplotlib
    - seaborn
    - scikit-learn
    - nltk
    - pytest
