---
- name: Install pyenv and python dependencies
  homebrew:
    name:
      - pyenv
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
    state: present

# If pyenv fails, check https://github.com/pyenv/pyenv/wiki/Common-build-problems#build-failed-error-the-python-zlib-extension-was-not-compiled-missing-the-zlib
- name: python versions
  command: pyenv install {{ item }}
  register: pyenv_install_result
  failed_when: >
    pyenv_install_result.rc != 0
    # and  pyenv_install_result.stderr_lines != ["pyenv: /Users/chainz/.pyenv/versions/" + item + " already exists"]
  loop: '{{ pyenv_python_versions }}'


- name: python versions active
  command: pyenv global {{ pyenv_python_versions|join(" ") }}


- name: python versions shims rehashed
  # Needs running after every update of pyenv, at least, to fix the pyenv shims
  command: pyenv rehash

- name: python versions latest Cython, pip, and pip-tools
  pip:
    name:
      - pip
      - pip-tools
    state: latest
    executable: '~/.pyenv/versions/{{ item }}/bin/pip{% if "pypy3" in item %}3{% endif %}'
  environment:
    PIP_REQUIRE_VIRTUALENV: ""
  loop: '{{ pyenv_python_versions }}'

- name: Install pip packages on first env
  pip:
    requirements: requirements.txt
    state: latest
    executable: '~/.pyenv/versions/{{ pyenv_python_versions[0] }}/bin/pip'
  environment:
    PIP_REQUIRE_VIRTUALENV: ""

- name: Configure Jupyter theme
  shell: jt -t monokai -fs 11 -tfs 12 -nfs 14 -cellw 70% -T -vim

- name: Install jupyter extensions
  shell: "conda install -y -c conda-forge {{ item }}"
  loop:
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
    - ipywidgets

# https://github.com/uploadcare/pillow-simd
- name: Install Pillow-SIMD
  shell: 'pip uninstall -y pillow; CC="cc -mavx2" pip install -U --force-reinstall pillow-simd'
