- name: generate SSH key "{{ssh_key_filename}}"
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    ssh_key_passphrase: "{{ ssh_passphrase }}"
    ssh_key_comment: "{{ ansible_user }}@{{ hostname }}"
    force: no

- name: .ssh permissions
  file:
    path: /home/jjgo/.ssh
    mode: '0700'

- name: Public key permissions
  file:
    path: /home/jjgo/.ssh/id_ed25519.pub
    mode: '0644'

- name: Private key permissions
  file:
    path: /home/jjgo/.ssh/id_ed25519
    mode: '0600'

- name: Authorized keys permissions
  file:
    path: /home/jjgo/.ssh/authorized_keys
    mode: '0600'

- name: Add github to known hosts
  blockinfile:
    path: /home/jjgo/.ssh/known_hosts
    block: |
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      github.mit.edu ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOhMLcf5HaMo5uFvtt5XYyvQeeAsZ3sPH6QApKUxmZiQcU1vvTCwGgssKzVpQQcdWeArRltjCxnD+p7iaVWuKls=
    state: present
    create: yes
